resolver: nightly-2021-02-12
packages:
  - ./persistent
  - ./persistent-template
  - ./persistent-sqlite
  - ./persistent-test
    # - ./persistent-mongoDB
  - ./persistent-mysql
  - ./persistent-postgresql
  - ./persistent-redis
  - ./persistent-qq

extra-deps:
  - bson-0.3.2.8
  - hedis-0.12.8
  - HTTP-4000.3.14
  - th-lift-instances-0.1.14

nix:
  pure: true
  enable: true
  packages: [ zlib postgresql mysql80 pcre mysql-client zstd openssl ]