resolver: lts-14.27
packages:
  - ./persistent
  - ./persistent-template
  - ./persistent-sqlite
  - ./persistent-test
  - ./persistent-mongoDB
  - ./persistent-mysql
  - ./persistent-postgresql
  - ./persistent-redis
  - ./persistent-qq

nix:
  pure: true
  enable: true
  packages: [ zlib postgresql mysql80 pcre mysql-client zstd openssl ]
